spring.application.name=nthnode-auth-server
server.port=9000

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true

info.app.name=nthNode Auth Server
info.app.version=@project.version@
